# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasksubmission_grading_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='extra',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='task',
            name='docker_image',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='grading_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='grading_image',
            field=models.CharField(default='', max_length=1023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='testing_image',
            field=models.CharField(default='', max_length=1023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklog',
            name='marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='max_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='tasks.TaskStep'),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='max_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskstep',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='broken',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='max_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='action',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('GRADING_STARTED', 'Grading started'), ('REGRADING_STARTED', 'Regrading started'), ('SUCCEEDED', 'Succeeded'), ('PARTIALLY_SUCCEEDED', 'Partially succeeded'), ('FAILED', 'Failed'), ('BROKE', 'Broke')], max_length=31),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='order',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='taskstep',
            name='input_source',
        ),
        migrations.RemoveField(
            model_name='taskstep',
            name='output_source',
        ),
        migrations.AlterUniqueTogether(
            name='taskstep',
            unique_together=set([('task', 'slug')]),
        ),
    ]
